build_image:  
  stage: build  

  image: docker:stable


  before_script:
    - docker info

  script:
    - docker login -u gitlab-ci-token -p "$CI_BUILD_TOKEN" $CI_REGISTRY
    - docker build -t "$CI_REGISTRY_IMAGE:D3M_Your_Team_Image_Name" -f Dockerfile .
    - docker push "$CI_REGISTRY_IMAGE:D3M_Your_Team_Image_Name"

  only:
    - master

  #uncomment to specify which executor to use
  tags:
    #uncomment to run with docker runner
    - docker
    #uncomment to  run with shell runner
    #- shell
