apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    app: ClientApp
spec:
  replicas: 13
  selector:
    matchLabels:
      app: ClientApp
  template:
    metadata:
      labels:
        app: ClientApp
    spec:
      containers:
      - name: sklearn-pmlb-client
        image: registry.datadrivendiscovery.org/gversteeg/sklearn-pmlb-benchmarks:D3M_sklearn-pmlb-benchmarks
        imagePullPolicy: Always
        env:
        - name: D3MINPUTDIR
          value: "/input"
        - name: D3MOUTPUTDIR
          value: "/output"
        - name: D3MTYPE
          value: "loop_client"
        - name: D3MCPU
          value: "1"
        - name: D3MRAM
          value: "512Mi"
        - name: D3MTIMEOUT
          value: "10"
        - name: D3MHOST
          value: "172.16.16.16"
        - name: D3MPORT
          value: "3000"
        resources:
          requests:
            memory: 512Mi
            cpu: 1
      imagePullSecrets:
      - name: regcred
