apiVersion: v1
kind: Pod
metadata:
  name: d3m-pmlb-scheduler-pod
  labels:
    app: SchedulerApp
spec:
  restartPolicy: Never
  containers:
  - name: d3m-sklearn-pmlb-benchmarks
    image: registry.datadrivendiscovery.org/gversteeg/sklearn-pmlb-benchmarks:D3M_sklearn-pmlb-benchmarks
    env:
    - name: D3MINPUTDIR
      value: "/input"
    - name: D3MOUTPUTDIR
      value: "/output"
    - name: D3MTYPE
      value: "scheduler"
    - name: D3MNUMCLIENTS
      value: "15"
    volumeMounts:
      - name: output-data
        mountPath: /output
        readOnly: false
    resources:
      requests:
        memory: 512Mi
        cpu: 1
  imagePullSecrets:
  - name: regcred
  volumes:
  - name: output-data
    persistentVolumeClaim:
      claimName: eval-output-pv-claim
